experiment_name: "poom_demo"

# Simulation
seed: 42
device: "auto"          # "auto" | "cpu" | "cuda"
dtype: "float32"
num_particles: 2048
box_size: 100.0         # side length of periodic square (arbitrary units)
G: 1.0                  # gravitational constant (toy)
softening: 0.5          # Plummer softening length
dt: 0.02
steps: 1500
save_every: 100

# Initial conditions
ic:
  distribution: "uniform_jitter"   # "uniform_jitter" | "gaussian"
  jitter_sigma: 0.5
  vel_sigma: 0.05

# Rendering
render:
  grid_size: 256
  cmap: "magma"
  dpi: 160
  vmin: null
  vmax: null

# IO
out_dir: "outputs"
